#!/usr/bin/env python3
"""Split Wanted Sans without removing any supported Unicode characters.

Run with fonttools[woff]==4.59.2 in an isolated Python environment.
"""
from collections import defaultdict
import hashlib
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

APP = Path(__file__).resolve().parents[1]
FONT_DIR = APP / "app/fonts/wanted-sans"
SOURCE = FONT_DIR / "WantedSansVariable.woff2"
OUTPUT = FONT_DIR / "subsets"
CSS = APP / "app/fonts/wanted-sans.css"
PUBLIC = APP / "public/fonts/wanted-sans"


def unicode_ranges(codepoints):
    points = sorted(codepoints)
    ranges = []
    first = last = points[0]
    for point in points[1:]:
        if point == last + 1:
            last = point
        else:
            ranges.append((first, last))
            first = last = point
    ranges.append((first, last))
    return ", ".join(
        f"U+{first:X}" if first == last else f"U+{first:X}-{last:X}"
        for first, last in ranges
    )


def axes(font):
    return [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in font["fvar"].axes]


def main():
    source = TTFont(SOURCE, recalcTimestamp=False)
    original_cmap = source.getBestCmap()
    supported = set(original_cmap)
    original_axes = axes(source)
    latin = {point for point in supported if point <= 0xFF}
    # Existing copy only determines a frequently used chunk. Every other glyph
    # remains available in range chunks, including future and user-entered text.
    copy_points = set()
    corpus = sorted((APP / "messages").glob("*.json"))
    corpus.append(APP / "lib/seo-copy.ts")
    corpus.extend(sorted((APP / "components").rglob("*.tsx")))
    for path in corpus:
        copy_points.update(ord(char) for char in path.read_text())
    common = (copy_points & supported) - latin
    chunks = {"latin": latin, "common": common}
    remaining = defaultdict(set)
    for point in sorted(supported - latin - common):
        remaining[point // 512].add(point)
    chunks.update({f"range-{block * 512:04x}": points for block, points in sorted(remaining.items())})
    OUTPUT.mkdir(exist_ok=True)
    css = ["/* Generated by scripts/subset-wanted-sans.py; preserve full original glyph coverage. */"]
    manifest = {"source_bytes": SOURCE.stat().st_size, "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(), "axes": original_axes, "chunks": []}
    observed = set()
    for name, points in chunks.items():
        font = TTFont(SOURCE, recalcTimestamp=False)
        options = subset.Options()
        options.flavor = "woff2"
        options.recalc_timestamp = False
        options.layout_features = ["*"]
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=points)
        subsetter.subset(font)
        path = OUTPUT / f"{name}.woff2"
        font.save(path)
        generated = TTFont(path)
        generated_cmap = generated.getBestCmap()
        actual = set(generated_cmap)
        assert actual == points, f"Glyph coverage changed in {name}"
        assert not (observed & actual), f"Overlapping range in {name}"
        assert axes(generated) == original_axes, f"Variable axes changed in {name}"
        for point, glyph in generated_cmap.items():
            assert generated["hmtx"].metrics[glyph] == source["hmtx"].metrics[original_cmap[point]], f"Glyph metrics changed: {point:X}"
        observed.update(actual)
        ranges = unicode_ranges(actual)
        chunk = {"name": name, "bytes": path.stat().st_size, "codepoints": len(actual), "unicode_range": ranges}
        url = f"./wanted-sans/subsets/{name}.woff2"
        if name == "common":
            digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
            PUBLIC.mkdir(parents=True, exist_ok=True)
            public_path = PUBLIC / f"common-{digest}.woff2"
            path.replace(public_path)
            url = f"/fonts/wanted-sans/{public_path.name}"
            chunk["filename"] = public_path.name
            chunk["public_path"] = url
            manifest["common_preload"] = url
        manifest["chunks"].append(chunk)
        if name != "latin":
            css.append(f'''@font-face {{
  font-family: "Wanted Sans";
  src: url("{url}") format("woff2");
  font-style: normal;
  font-weight: 400 1000;
  font-display: swap;
  unicode-range: {ranges};
}}''')
    assert observed == supported, "Original Unicode coverage was lost"
    CSS.write_text("\n\n".join(css) + "\n")
    (OUTPUT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"Verified {len(observed)} codepoints and {len(chunks)} disjoint chunks; variable axes: {original_axes}")
    for chunk in manifest["chunks"][:2]:
        print(f"{chunk['name']}: {chunk['bytes']} bytes, {chunk['codepoints']} codepoints")


if __name__ == "__main__":
    main()
